# Generated by Django 5.1.7 on 2025-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_age', models.PositiveIntegerField()),
                ('working_job', models.CharField(max_length=100)),
                ('working_duration', models.PositiveIntegerField()),
                ('worker_phone', models.CharField(max_length=15)),
                ('worker_payment', models.PositiveIntegerField()),
                ('worker_address', models.CharField(max_length=255)),
                ('worker_image', models.ImageField(upload_to='worker_photos/')),
            ],
        ),
    ]
