# Generated by Django 5.1.7 on 2025-07-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
