# Generated by Django 5.1.7 on 2025-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_age', models.PositiveIntegerField()),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_dryness', models.PositiveIntegerField()),
                ('crop_bread', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('crop_description', models.TextField(blank=True, null=True)),
                ('crop_quantity', models.PositiveIntegerField(help_text='In kg or appropriate unit')),
                ('expected_price', models.PositiveIntegerField(help_text='In ₹ or appropriate currency')),
                ('farming_location', models.CharField(max_length=255)),
                ('cropping_duration', models.CharField(help_text='e.g., 3 months, 90 days', max_length=100)),
            ],
        ),
    ]
