# Generated by Django 5.1.7 on 2025-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
