# Generated by Django 5.1.7 on 2025-07-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crops_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='crop_image',
            field=models.ImageField(default='default.jpg', upload_to='crop_images/'),
        ),
    ]
