# Generated by Django 5.1.7 on 2025-07-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_crops_crop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crops',
            old_name='cropping_duration',
            new_name='croping_duration',
        ),
    ]
