# Generated by Django 5.1.7 on 2025-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_rename_cropping_duration_crops_croping_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
