# Generated by Django 5.1.7 on 2025-07-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_alter_crops_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='crop_image',
            field=models.ImageField(upload_to='crop_images/'),
        ),
    ]
