# Generated by Django 5.1.7 on 2025-07-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_address', models.CharField(max_length=100)),
                ('purchase_quantity', models.PositiveIntegerField()),
                ('negotiation_price', models.PositiveIntegerField()),
                ('delivery_date', models.PositiveIntegerField()),
            ],
        ),
    ]
