# Generated by Django 5.1.7 on 2025-07-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyier',
            name='delivery_date',
        ),
    ]
