# Generated by Django 5.1.7 on 2025-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyier', '0002_remove_buyier_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyier',
            name='crop_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buyier',
            name='farmer_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
