# Generated by Django 5.1.7 on 2025-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyier', '0003_buyier_crop_name_buyier_farmer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyier',
            name='buyer_phone',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
