# Generated by Django 5.1.7 on 2025-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyier', '0004_buyier_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyier',
            name='buyer_phone',
            field=models.PositiveIntegerField(),
        ),
    ]
